version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      /bin/sh -c "python3 database_operations.py &&
      streamlit run app.py --server.fileWatcherType poll"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama  # Use a local project folder for models
    environment:
      - OLLAMA_LOAD_TIMEOUT=15m
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["ollama", "serve", "--host", "0.0.0.0"]